name: DNSControl Push

on:
  push:
    branches: [main]

jobs:
  prepare:
    uses: ./.github/workflows/prepare.yml
  push:
    name: Push DNS changes
    needs: prepare
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Download DNSControl binaries
        uses: actions/download-artifact@v4.1.7
        with:
          name: lib
          path: lib
      - name: Download compiled JS
        uses: actions/download-artifact@v4.1.7
        with:
          name: out
          path: out
      - name: Make binaries executable
        run: chmod +x dnscontrol*
        working-directory: lib
        shell: bash
      - name: Pull CF secrets from Vault
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.zhr.one
          role: dns
          path: github
          method: jwt
          jwtGithubAudience: sigstore
          secrets: |
            /ci-cd/dns/cloudflare/push CF_API
      - name: Generate and push records
        run: ../lib/dnscontrol-Linux --diff2 push
        working-directory: out
        shell: bash
